### ISSUE TITLE
Move hosting environment to Google Cloud Run

### ISSUE THREAD

**Issue by simoneb** [fastify/dependabot-merge-action-app#22]
## 🚀 Feature Proposal

The application should be hosted on Google Cloud Run. 

- [x] Its deployment should be automated when commits are made to the master branch
- [x] The GitHub Action using this app should be changed to point to the new server 
- [x] The documentation needs to be updated
- [x] The old app needs to be kept around until the old version stops being used
- [x] reset the temporary api-url override done in [autocannon-ui](https://github.com/nearform/autocannon-ui/blob/master/.github/workflows/ci.yml#L40)

## Motivation

The Heroku app is hosted on a personal, free account which does not fit the purpose of this action.

## How to do it

- inspire from how Titus infrastructure is set up: https://github.com/nearform/titus/. It uses terraform, github actions and gcp scripts to deploy the application

**Comment by mcollina** [comment]
I agree. I'll try to see if we can set it up.

**Comment by simoneb** [comment]
@mcollina CD to GCR is now available and deploying to a project in the NearForm account. The readme describes how to set it up so you can move it to another account. Once this is done, we must change the action so that it points to that API. For any questions you can ask @CledersonE

**Comment by mcollina** [comment]
Which settings should I use to create the app?

![Screenshot 2021-05-24 at 17 44 57](https://user-images.githubusercontent.com/52195/119372674-ddbb2a80-bcb7-11eb-819e-212e87f5a620.png)

**Comment by CledersonE** [comment]
@mcollina I've updated the readme section of "How to deploy" and send the PR to @simoneb. Once is approved you can continue with the deploy.

**Comment by mcollina** [comment]
It's deployed: https://fastify-dependabot-merge-app-5uewp47fja-uc.a.run.app/.

**Comment by simoneb** [comment]
Awesome. I changed https://github.com/nearform/autocannon-ui/blob/master/.github/workflows/ci.yml#L45 to point to it. We need to wait until a package is bumped in that repo to see if the action works and then we can propagate this change by making it the default in the automerge action.

**Comment by simoneb** [comment]
This is now complete, the only thing missing is to decommission the old app which is still used by old versions of the actions. I'll keep an eye on the metrics over time then as some point we'll kill it. I'll go back to this in a couple of weeks or so.

**Comment by simoneb** [comment]
I'm going to decommission the app next week. I updated the action's readme with this information and sent emails/pull requests to all the projects which, based on the logs enabled a few days ago, are still using an old version of the app.

**Comment by simoneb** [comment]
This is now complete. The old app running on Heroku has been decommissioned.

**Comment by simoneb** [comment]
See https://github.com/fastify/github-action-merge-dependabot/commit/8ddd309b3f1e89233ff236e2c7fa9fd4f212e5ef
